[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "erl "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "pulumi "
